<head>
   <?= $this->headScript(); ?>
</head>   
<body>
    <h3>CAMERE:</h3>
    <?php foreach ($this->catalogo as $CAT) :?>
<h3> <?php echo' <class="title">' . $CAT->tipo . '' ?> </h3>
	<img src="<?php echo $this->baseUrl() . '/images/'.$CAT->foto.'' ?> "  class="cat-img" >
        
        <h4>DESCRIZIONE:</h4>
         <?php echo' <class="title">' . $CAT->descrizione . '' ?>
        
	<br><br>
	<?php endforeach ?>
</body>