

<?php $prenotazione = new Zend_Session_Namespace('data_arrivo');
       $prenotazione = new Zend_Session_Namespace('data_partenza');
       $prenotazione = new Zend_Session_Namespace('giorni'); 
       $cod = new Zend_Session_Namespace('codicecamera');
       $serv = new Zend_Session_Namespace('richiestaservizi');
       $ser = new Zend_Session_Namespace('listaservizi');?>

       
        <?php echo $prenotazione->data_arrivo ?><br>
       <?php echo $prenotazione->data_partenza ?><br>
       <?php echo $prenotazione->giorni ?><br>
        <?php echo $cod->codicecamera ?><br>
        <?php if($serv->richiestaservizi)
        {echo 'Hai richiesto i seguenti servizi: <br>';
         foreach ($ser->listaservizi as $servi)
        {echo $servi['tiposervizio'].$servi['valore'].'<br>';}
        }
        else{echo'Non hai richiesto servizi';}?><br>
        
        