<h3>DISPONIBILIT&Aacute; CAMERA : <?php echo $this->Camera ?></h3>

<?php if($this->prenotazioni->count()==0)
{
    echo '<tr><td colspan="2"><h4>La camera è sempre disponibile </h4></td></tr>';
}else{
 
 foreach($this->prenotazioni as $pren) 
 {  echo '<tr><td><h4>PRENOTATA DAL: </h4></td><td>'.$pren->data_inizio_pren.'</td></tr>'; 
 echo '<tr><td><h4>AL: </h4></td><td>'.$pren->data_fine_pren.'</td></tr>';} 
}
echo '</td></tr>' ?>
</table>
<br>
 <div class="static">
 <h3>SCEGLI L'INTERVALLO</h3>
 <?=$this->dataprenotazioneForm; ?>
      
</div>