<head>
   <?= $this->headScript(); ?>

<script  language="JavaScript">
var i = 0;
var path = new Array();
 
// LIST OF IMAGES
path[0] = "images/hotel1.jpg";
path[1] = "images/hotel2.jpg";
path[2] = "images/hotel3.jpg";
path[3] = "images/hotel4.jpg";

window.onload=swapImage;
</script>
</head>

<body>


    <img width="100%"  name="slide" src="images/hotel1.jpg" />
    
    <a href="<?=$this->baseUrl('/../docs/Relazione.pdf')?>" target="_blank">Relazione</a>
    
</body>