<div>
    <h3> LISTA PRENOTAZIONI</h3>   
    
           
	<?php foreach ($this->lista as $lis) :?>
    <table>
        <tr><td><h4>DATA PRENOTAZIONE: </h4></td><td><?php echo' <class="title">' . $lis['prenotazione']->data_prenotazione . '' ?></td></tr>
        <tr><td><h4>CAMERA NUMERO: </h4></td><td><?php echo' <class="title">' . $lis['prenotazione']->codice_camera . '' ?></td></tr>
        <tr><td><h4>TIPO CAMERA: </h4></td><td><?php echo' <class="title">' . $lis['prenotazione']->tipo_camera . '' ?></td></tr>
        <tr><td><h4>DATA ARRIVO: </h4></td><td><?php echo' <class="title">' . $lis['prenotazione']->data_inizio_pren . '' ?></td></tr>
        <tr><td><h4>DATA PARTENZA: </h4></td><td><?php echo' <class="title">' . $lis['prenotazione']->data_fine_pren . '' ?></td></tr>
        <tr><td><h4>SERVIZI AGGIUNTIVI: </h4></td><td>
        <?php if($lis['prenotazione']->richiesta_servizi)  
        {   foreach ($lis['servizi'] as $serv) 
        {echo $serv->tipo_servizio.'<br>';
        }}
        else
        {echo 'Non hai richiesto alcun servizio';}
        
         ?></td></tr>
        <tr><td><h4>PREZZO TOTALE: </h4></td><td><?php echo' <class="title">' . $lis['prenotazione']->prezzo_totale . ' '.'€' ?></td></tr>
        
    </table>
    <?php $now=new Zend_Date() ?>
    <?php $dpren=new Zend_Date($lis['prenotazione']->data_inizio_pren) ?>
    
       <?php if($dpren->compare($now)> 0)
   { echo'<a href="'. $this->url(array(
                        'controller' => 'utente',
                        'action'     => 'deleteprenotazione',
                        'codice' => $lis['prenotazione']->cod_prenotazione), 
                        'default' ,true
                    ) 
                 .'" ><button>CANCELLA PRENOTAZIONE</button></a>'
           . '<a href="'. $this->url(array(
                        'controller' => 'utente',
                        'action'     => 'modificaprenotazione',
                        'codice' => $lis['prenotazione']->cod_prenotazione), 
                        'default' ,true
                    ) 
                 .'" ><button>MODIFICA PRENOTAZIONE</button></a>';}
       ?>  
    <a href="<?= $this->url(array(
                        'controller' => 'utente',
                        'action'     => 'stampaprenotazione',
                        'codice'         =>$lis['prenotazione']->cod_prenotazione
						), 
                        'default',true
                    ); 
        ?>"><button>STAMPA PRENOTAZIONE</button></a>
    <br><br>
	<?php endforeach ?>
</div>
<div>
	 <!-- Paginazione -->	
	  <?php if($this->prenotazioni instanceof Zend_Paginator) {
	  		echo $this->paginationControl($this->prenotazioni,'Sliding','utente/_paginatorlistaprenotazioni.phtml');
	  } 
          ?>
       
</div>