<div>
    <h3> LISTA CAMERE DISPONIBILI</h3>   
    
           
	<?php foreach ($this->camerelibere as $cam) :?>
    <table>
        <tr><td><h4>CAMERA NUMERO: </h4></td><td><?php echo' <class="title">' . $cam->cod_camera . '' ?></td></tr>
        <tr><td><h4>TIPO CAMERA:   </h4></td><td><?php echo' <class="title">' . $cam->tipo . '' ?></td></tr>
        <tr><td><h4>TV:            </h4></td><td> 
            <?php if($cam->tv)  
        {   
           echo 'La camera è dotata di tv'.'<br>';}
        else
        {echo 'La camera non è dotata di tv';}
        
         ?></td></tr>
        <tr><td><h4>INTERNET:            </h4></td><td> 
            <?php if($cam->internet)  
        {   
           echo 'La camera è dotata di rete wifi'.'<br>';}
        else
        {echo 'La camera non è dotata di rete wifi';}
        
         ?></td></tr>
        <tr><td><h4>COSTO TOTALE:  </h4></td><td><?php echo' <class="title"><h3>' . $cam->prezzo_camera . ' '.'€</h3>' ?></td></tr>
    </table>
	<?php endforeach ?>
</div>
