<div>
    <h3> LISTA CAMERE DISPONIBILI</h3>   
    
           
	<?php foreach ($this->camerelibere as $cam) :?>
    <table>
        <tr><td rowspan="5"><img src="<?php echo $this->baseUrl() . '/images/'.$cam['camera']->foto.'' ?>" class="foot-img"></td><td><h4>TIPO CAMERA:   </h4></td><td class="camere"><?php echo' <class="title">' . $cam['camera']->tipo . '' ?></td></tr>
        <tr><td><h4>TV SATELLITARE:            </h4></td><td class="camere"> 
            <?php if($cam['camera']->tv)  
        {   
           echo 'SI'.'<br>';}
        else
        {echo 'NO';}
        
         ?></td></tr>
        <tr><td><h4>INTERNET:            </h4></td><td class="camere"> 
            <?php if($cam['camera']->internet)  
        {   
           echo 'SI'.'<br>';}
        else
        {echo 'NO';}
        
         ?></td></tr>
        <tr><td><h4>COSTO TOTALE:  </h4></td><td class="camere"><?php echo' <class="title"><h3>' . $cam['prezzo'] . ' '.'€</h3>' ?></td></tr>
    </table>
     <?php echo'<a href="'. $this->url(array(
                        'controller' => 'utente',
                        'action'     => 'sceltaservizi',
                        'codicecamera' => $cam['camera']->cod_camera 
                        ),
                        'default' ,true
                    ) 
                 .'" ><button>PRENOTA</button></a>';
       ?> 
    <br>
	<?php endforeach ?>
</div>
