<head>
   <?= $this->headScript(); ?>
</head>  

<table>
    <th class="profilo"><h2> IL MIO PROFILO</h2></th><th class="profilo"></th>
<tr><td>NOME</td><td> <?php echo' <class="title">' . $this->profilo->nome . '' ?> </td></tr>
<tr><td>COGNOME</td><td> <?php echo' <class="title">' . $this->profilo->cognome . '' ?> </td></tr>
<tr><td>DATA DI NASCITA</td><td> <?php echo' <class="title">' . $this->profilo->data_nascita . '' ?></td></tr>
<tr><td>CITTA</td><td> <?php echo' <class="title">' . $this->profilo->citta . '' ?> </td></tr>
<tr><td>INDIRIZZO</td><td> <?php echo' <class="title">' . $this->profilo->indirizzo . '' ?> </td></tr>
<tr><td>NUMERO DI TELEFONO</td><td> <?php echo' <class="title">' . $this->profilo->numero_telefono . '' ?> </td></tr>
<tr><td>EMAIL</td><td> <?php echo' <class="title">' . $this->profilo->email . '' ?> </td></tr>
</table>