 
<body>
    <h3>SERVIZI:</h3>
    <?php foreach ($this->servizi as $SER) :?>
<h3> <?php echo' <class="title">' . $SER->tipo . '' ?> </h3>
	<img src="<?php echo $this->baseUrl() . '/images/'.$SER->foto.'' ?> "  class="cat-img" >
        <h4>DESCRIZIONE:</h4>
        <?php echo' <class="title">' . $SER->descrizione . '' ?>
            	<br><br>
	<?php endforeach ?>
                         <!-- Paginazione -->	
	  <?php if($this->servizi instanceof Zend_Paginator) {
	  		echo $this->paginationControl($this->servizi,'Sliding','staff/_paginatorcatalogoservizi.phtml');
	  } 
          ?>
</body>