<?php foreach ($this->listapren as $pren) :?>
<?php echo $pren['prenotazione']->cod_prenotazione.' ' ?>
<?php echo $pren['prenotazione']->codice_camera.' ' ?>
<?php echo $pren['prenotazione']->username.' ' ?>
<?php echo $pren['prenotazione']->data_prenotazione.' ' ?>
<?php echo $pren['prenotazione']->data_inizio_pren.' ' ?>
<?php echo $pren['prenotazione']->data_fine_pren.' ' ?>
<?php echo $pren['prenotazione']->richiesta_servizi.' ' ?>

<?php foreach ($pren['servizi'] as $serv)
{
    echo $serv->tipo_servizio;
} ?>
<?php //Zend_Debug::dump($this->date);?>
<br>
<?php endforeach; ?>

    