 
<?php foreach ($this->listapren as $pren) :?>
<?php if($pren['nominativo']==null){}
else{
echo'<table border="2">
    <tr><td width="40%"><h5>NOMINATIVO:</h5></td><td align="left">'.$pren['nominativo']->nome.' '.$pren['nominativo']->cognome.'</td></tr>
    <tr><td width="40%"><h5>CAMERA NUMERO:</h5></td><td align="left">'.$pren['prenotazione']->codice_camera .'</td></tr>
    <tr><td width="40%"><h5>DAL:</h5></td><td align="left">'.$pren['prenotazione']->data_inizio_pren .'</td></tr>
    <tr><td width="40%"><h5>AL:</h5></td><td align="left">'.$pren['prenotazione']->data_fine_pren .'</td></tr>
    <tr><td width="40%"><h5>SERVIZI:</h5></td><td align="left">'; if($pren['prenotazione']->richiesta_servizi)
    {foreach ($pren['servizi'] as $serv)
{  
    echo $serv->tipo_servizio.'<br>';
    }}else echo 'Non è stato richiesto alcun servizio </td></tr> 
    <br>';
    $link=$this->url(array(
                        'controller' => 'staff',
                        'action'     => 'dettaglipren',
                        'codicepren' => $pren['prenotazione']->cod_prenotazione
						), 
                        'default',true
                    );
    echo'<tr><td colspan="2" align="right"><a href="'.$link.'  
"><button>DETTAGLI</button></a></td></tr>
<br>
</table>';
}?>
<?php endforeach; ?>
      
