<head>
   <?= $this->headScript(); ?>
</head>   
<body>
	<h1>Chi siamo ?</h1>
        <h4>HOTEL UNIVPM</h4>
	<p>Mario Rossi, fondatore di RossiViaggi, ha voluto riportare all’Hotel Univpm l’esperienza di una vita e di un grande gruppo, punto di riferimento per il turismo in Italia e nel mondo, attraverso un’offerta caratterizzata da vacanze di qualità e viaggi all’insegna del relax, del benessere e del divertimento.

Nato ad Ancona, ha fondato qui la sua impresa, dove ha tutt’ora la sede principale, convinto che creare sviluppo e occupazione nel suo territorio fosse un modo per rispettare le sue origini. E da queste origini, dall’amato hotel di famiglia, l’Hotel Univpm, oggi riparte per una nuova avventura. Le radici della zona e l’esperienza di Mario Rossi permettono di recuperare il meglio della grande tradizione alberghiera e tracciare una rotta verso un modello migliore di ospitalità. Questo rappresenta l’Hotel Univpm: l’ideale alberghiero di Mario Rossi per Ancona, per le Marche. Un innesto innovativo, un hotel di lusso e di design, nato su radici solide.

Si torna a casa e in questa casa verrete accolti da una allure che riporta alle origini della nascita della tradizione alberghiera adriatica, gli anni ’50, insieme a suggestioni internazionali: l’East Coast americana, gli Hamptons, a cui il concept stilistico dell’Hotel Univpm si riferisce.

La concezione degli spazi, i colori discreti, le ampie aperture con vista sul mare che raccolgono i suoi colori mutevoli, il rimando agli stili e al gusto della tradizione velica, fanno dell'Univpm un hotel dove eleganza, riservatezza e fascino sono valori indissolubili. Senza dimenticare il wellness, mentale e fisico, assicurato dai trattamenti e dai pacchetti del centro benessere con Spa vista mare.</p>
</body>