<?php echo $this->doctype() ?>
<html>
<head>
	<?= $this->headMeta(); ?>
    <?= $this->headLink(); ?>  
</head>
<body>
<div id="container">
     <header>
    	<h1><a href="<?= $this->url( array( 'controller' => 'staff',
		'action' => 'index')) ?>">HOTEL       <span>U</span>NIVPM</a></h1>
        è buono qui, è buono qui
    </header>
    <nav>
    	<?= $this->render('topnav_staff.phtml') ?>
    </nav>

	

    <div id="body">

		<section id="content">
			
	    <article>
							
  		<?php echo $this->layout()->content ?>  
  		
		</article>
		
        </section>
        
        <aside class="sidebar">
	
    	
            
        </aside>
        
    	<div class="clear"></div>
    </div>
    
    <footer>

    	<?= $this->render('footer.phtml') ?>
       
    </footer>
</div>
</body>
</html>