
<ul>	
               <li>
                    <h4><b>BENVENUTO</b></h4>
                    
                    <ul>
                   <li><a href="<?= $this->url(array(
                        'controller' => 'utente',
                        'action'     => 'profilo',
						), 
                        'default',true
                    ); 
                 ?>" >PROFILO UTENTE</a></li>
                            <li><a href="<?= $this->url(array(
                        'controller' => 'utente',
                        'action'     => 'catalogocamere',
						), 
                        'default',true
                    ); 
                 ?>" >CATALOGO CAMERE</a></li> 
                        <li><a href="<?= $this->url(array(
                        'controller' => 'utente',
                        'action'     => 'catalogoservizi',
						), 
                        'default',true
                    ); 
                 ?>" >CATALOGO SERVIZI</a></li>
                   <li><a href="<?= $this->url(array(
                        'controller' => 'utente',
                        'action'     => 'dataprenotazione',
						), 
                        'default',true
                    ); 
                 ?>" >EFFETTUA PRENOTAZIONE</a></li>
                   <li><a href="<?= $this->url(array(
                        'controller' => 'utente',
                        'action'     => 'listaprenotazioni',
						), 
                        'default',true
                    ); 
                 ?>" >PRENOTAZIONI EFFETTUATE</a></li>
                   
               
                        
          
                    </ul>
                </li>
                
               
                
</ul>