
<ul>	
               <li>
                    <h4><b>BENVENUTO</b></h4>
                    
                    <ul>
                   <li><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'profilo',
						), 
                        'default',true
                    ); 
                 ?>" >PROFILO UTENTE</a></li>
                    
                   <li><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'filtraprenotazioni',
						), 
                        'default',true
                    ); 
                 ?>" >LISTA PRENOTAZIONI</a></li>
                   <li><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'disponibilita',
						), 
                        'default',true
                    ); 
                 ?>" >DISPONIBILIT&Aacute;</a></li>
                   <li>
        		<a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'catalogocamere',
						), 
                        'default',true
                    ); 
                 ?>" >CATALOGO CAMERE</a></li>
                <li>
        		<a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'catalogoservizi',
						), 
                        'default',true
                    ); 
                 ?>"  >CATALOGO SERVIZI</a></li>
                   <li><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'insertutente',
						), 
                        'default',true
                    ); 
                 ?>" >INSERISCI UTENTE</a></li>
                   <li><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'listaclienti',
						), 
                        'default',true
                    ); 
                 ?>" >LISTA CLIENTI</a></li>
                   <li><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'listastaff',
						), 
                        'default',true
                    ); 
                 ?>" >LISTA STAFF</a></li>
                   <li><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'insertservizi',
						), 
                        'default',true
                    ); 
                 ?>" >INSERISCI SERVIZI</a></li> 
               
                        
          
                    </ul>
                </li>
                
               
                
</ul>