
<ul>	
               <li>
                    <h4><b>BENVENUTO</b></h4>
                    
                    <ul>
                   <li><a href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'profilo',
						), 
                        'default',true
                    ); 
                 ?>" >PROFILO UTENTE</a></li>
                    
                   <li><a href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'filtraprenotazioni',
						), 
                        'default',true
                    ); 
                 ?>" >LISTA PRENOTAZIONI</a></li>
                   <li><a href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'disponibilita',
						), 
                        'default',true
                    ); 
                 ?>" >DISPONIBILIT&Aacute;</a></li>
                   <li><a href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'catalogocamere',
						), 
                        'default',true
                    ); 
                 ?>" >CATALOGO CAMERE</a></li> 
                        <li><a href="<?= $this->url(array(
                        'controller' => 'staff',
                        'action'     => 'catalogoservizi',
						), 
                        'default',true
                    ); 
                 ?>" >CATALOGO SERVIZI</a></li>
               
                        
          
                    </ul>
                </li>
                
               
                
</ul>