<head>
   <?= $this->headScript(); ?>
</head>   
<div>
    <h3> LISTA DELLE F.A.Q.</h3>   
    <ul>
            
	<?php foreach ($this->faq as $FAQ) :?>
	<li> <?php echo' <class="title">' . $FAQ->domanda . '' ?> </li>
	<?php echo' <class="title">' . $FAQ->risposta . '' ?> 
	<br><br>
	<?php endforeach ?>
       
	</ul>
    <div align="right">
           <a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'insertfaq',
						), 
                        'default',true
                    ); 
?>"><button>INSERISCI NUOVA FAQ</button></a>
	</div>
</div>