<table>
    <tr><td><h3>NOME</h3></td><td><h3>COGNOME</h3></td><td></td><td></td></tr>   
<?php foreach ($this->staff as $ST) :?>

    <tr><td><h4><?php echo $ST->nome ?></h4></td><td><h4><?php echo $ST->cognome ?></h4></td><td><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'modificastaff',
                        'username'=>$ST->username
						), 
                        'default',true
                    ); 
?>"><button>MODIFICA</button></a></td><td><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'cancellastaff',
                        'username'=>$ST->username
						), 
                        'default',true
                    ); 
?>"><button>CANCELLA</button></a></td></tr>

<?php endforeach; ?>
</table>

