<table>
    <tr><td><h3>NOME</h3></td><td><h3>COGNOME</h3></td><td></td><td></td><td></td></tr>   
<?php foreach ($this->clienti as $CLI) :?>

    <tr><td><h4><?php echo $CLI->nome ?></h4></td><td><h4><?php echo $CLI->cognome ?></h4></td><td><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'updateutente',
                        'username'=>$CLI->username
						), 
                        'default',true
                    ); 
?>"><button>MODIFICA</button></a></td>
        <td><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'cancellacliente',
                        'username'=>$CLI->username
						), 
                        'default',true
                    ); 
?>"><button>CANCELLA</button></a></td>
    <td><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'statistiche',
                        'username'=>$CLI->username
						), 
                        'default',true
                    ); 
?>"><button>STATISTICHE</button></a></td></tr>

<?php endforeach; ?>
</table>

