 
<?php foreach ($this->listapren as $pren) :?>
<table border="2">
    <tr><td width="40%"><h5>NOMINATIVO:</h5></td><td align="left"><?php echo $pren['nominativo']->nome.' '.$pren['nominativo']->cognome ?></td></tr>
    <tr><td width="40%"><h5>CAMERA NUMERO:</h5></td><td align="left"><?php echo $pren['prenotazione']->codice_camera ?></td></tr>
    <tr><td width="40%"><h5>DAL:</h5></td><td align="left"><?php echo $pren['prenotazione']->data_inizio_pren ?></td></tr>
    <tr><td width="40%"><h5>AL:</h5></td><td align="left"><?php echo $pren['prenotazione']->data_fine_pren ?></td></tr>
    <tr><td width="40%"><h5>SERVIZI:</h5></td><td align="left"><?php if($pren['prenotazione']->richiesta_servizi)
    {foreach ($pren['servizi'] as $serv)
{  
    echo $serv->tipo_servizio.'<br>';
    }}else echo 'Non è stato richiesto alcun servizio' ?></td></tr> 
    <br>
    
    <tr><td colspan="2" align="right"><a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'dettaglipren',
                        'codicepren' => $pren['prenotazione']->cod_prenotazione
						), 
                        'default',true
                    ); 
?>"><button>DETTAGLI</button></a></td></tr>
<br>
</table>
<?php endforeach; ?>
      
