<div>
    <h3> LISTA CAMERE</h3>   
    
           
	<?php foreach ($this->camere as $cam) :?>
    <table>
        <tr><td rowspan="4"><img src="<?php echo $this->baseUrl() . '/images/'.$cam->foto.'' ?>" class="foot-img"></td>
            <td><h4>TIPO CAMERA:   </h4></td>
            <td class="camere"><?php echo' <class="title">' . $cam->tipo . '' ?></td>
        </tr>
        <tr>
            <td><h4>TV SATELLITARE:            </h4></td>
            <td class="camere"> 
            <?php if($cam->tv)  
            {   
           echo 'SI<br>';}
            else
                {echo 'NO';}
        
            ?></td>
        </tr>
        <tr>
            <td><h4>INTERNET:            </h4></td>
            <td class="camere"> 
            <?php if($cam->internet)  
            {   
             echo 'SI<br>';}
            else
            {echo 'NO';}
        
            ?></td>
        </tr>
        <tr>
            <td><h4>COSTO GIORNALIERO:  </h4></td>
            <td class="camere"><?php echo' <class="title"><h3>' . $cam->prezzo_camera. ' '.'€</h3>' ?></td>
        </tr>
        <tr>
            <td></td>
            <td colspan="2">
            <a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'updatedisponibilita',
                        'camera'      =>  $cam->cod_camera,
						), 
                        'default',true
                    ); 
            ?>"><button>Modifica Disponibilità</button></a>
            <a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'updatecamera',
                        'camera'      =>  $cam->cod_camera,
						), 
                        'default',true
                    ); 
            ?>"><button>Modifica</button></a>
            
            <a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'deletecamera',
                        'camera'      =>  $cam->cod_camera,
						), 
                        'default',true
                    ); 
            ?>"><button>Cancella</button></a></td>
        </tr>
    </table>
     
    <br>
	<?php endforeach ?>
     <a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'catalogocamere',), 
                        'default',true
                    ); 
            ?>"><button>INDIETRO</button></a>
  
        <a href="<?= $this->url(array(
                        'controller' => 'admin',
                        'action'     => 'insertcamera',
                        'tipo'      =>  $this->tipo
						), 
                        'default',true
                    ); 
            ?>"><button>INSERISCI NUOVA CAMERA</button></a>
   
    
</div>
