<h3>Statistiche cliente <?php echo $this->nominativo->cognome.'  '.$this->nominativo->nome ?></h3>
<h4>Spesa su base annuale</h4>

<table>
    <tr><td><h5>Anno</h5></td><td><h5>Spesa</h5></td></tr>
        <?php foreach ($this->totali as $anno ) :?>
    
            <tr><td><?php echo $anno['anno'] ?></td><td><?php echo $anno['spesa'].' €' ?></td></tr>
        <?php endforeach; ?>
    
</table>

<h4>Tipi di camere usate</h4>
<table>
    
        <?php foreach ($this->camere as $camera ) :?>
    
            <tr><td><?php echo $camera ?></td></tr>
        <?php endforeach; ?>
    
</table>

<h4>Tipi di servizi usati</h4>

<table>
    
        <?php foreach ($this->servizi as $serv ) :?>
    
            <tr><td><?php echo $serv ?></td></tr>
        <?php endforeach; ?>
    
</table>
